apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: cpu-instances
spec:
  minSize: 3
  maxSize: 10
  machineType: c5.large
  image: ami-0c94855ba95c71c99
  subnets:
    - us-west-1a
    - us-west-1b
    - us-west-1c
  nodeLabels:
    kops.k8s.io/instancegroup: cpu-instances
