apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-spot
spec:
  role: Node
  machineType: t3.medium
  image: ami-0c94855ba95c71c99
  maxSize: 5
  minSize: 1
  maxPrice: "1.0"
  subnets:
    - us-west-1a
    - us-west-1b
    - us-west-1c
